# 节点数目
node_num: 2

# 节点host
node_host: 
  - 192.168.200.51
  - 192.168.200.51
  # - 192.168.200.51

# 节点port
node_port:
  - 8001
  - 8002
  # - 8003

# 节点间连接数目
edge_num: 2
# 节点连接情况
node_edge:
 - 0: 1
 - 1: 0
#  - 2: 0
#  - 1: 0
#  - 3: 1